#!/usr/bin/perl

use strict;
use warnings;

my %replace = (
    'aemundo.co'              =>  'I18955.json.schedulesdirect.org',
    'amc.co'                  =>  'I90852.json.schedulesdirect.org',
    'animalplanet.co'         =>  'I18649.json.schedulesdirect.org',
	'aljazeera.co'            =>  'I49968.json.schedulesdirect.org',
    'antena3.co'              =>  'I16800.json.schedulesdirect.org',
    'arirang.co'              =>  'I28452.json.schedulesdirect.org',
	'axn.co'                  =>  'I26083.json.schedulesdirect.org',
    'azcorazon.co'            =>  'I61404.json.schedulesdirect.org',
    'azmundo.co'              =>  'I79968.json.schedulesdirect.org',
	'babytv.co'               =>  'I56036.json.schedulesdirect.org',
    'bbcworld.co'             =>  'I89542.json.schedulesdirect.org',
    'bloomberg.co'            =>  'I16829.json.schedulesdirect.org',
	'boomerang.co'            =>  'I26089.json.schedulesdirect.org',
	'cablenoticias.co'        =>  '',
	'canalclaro.co'           =>  '',
	'caracolhd.co'            =>  'I18567.json.schedulesdirect.org',
	'caracolinter.co'         =>  'I39719.json.schedulesdirect.org',
	'cartoon.co'              =>  'I19458.json.schedulesdirect.org',
	'cinecanal.co'            =>  'I16435.json.schedulesdirect.org',
	'cinelatino.co'           =>  'I15296.json.schedulesdirect.org', 	
	'cinedinamita.co'         =>  'I82420.json.schedulesdirect.org',
	'cinemax.co'              =>  '',
	'citytv.co'               =>  '',
	'clarocinema.co'          =>  'I97501.json.schedulesdirect.org',
	'claroconcert.co'         =>  'I72020.json.schedulesdirect.org',
	'claromusica.co'          =>  '',
	'clarosport.co'           =>  'I86779.json.schedulesdirect.org',
	'clarosportcol.co'        =>  '',
	'cnn.co'                  =>  'I58646.json.schedulesdirect.org',
	'cnnespanol.co'           =>  'I27773.json.schedulesdirect.org',
	'comedycentral.co'        =>  '',
	'depelicula.co'           =>  'I16288.json.schedulesdirect.org',
	'dhe.co'                  =>  'I81623.json.schedulesdirect.org',
	'discoverychannel.co'     =>  'I15798.json.schedulesdirect.org',
	'discoveryhyh.co'         =>  'I97571.json.schedulesdirect.org',
	'discoveryid.co'          =>  'I16048.json.schedulesdirect.org',
	'discoverykids.co'        =>  'I16680.json.schedulesdirect.org',	
	'discoveryscience.co'     =>  'I46610.json.schedulesdirect.org',	
	'tlc.co'                  =>  'I73822.json.schedulesdirect.org',
	'discoverytheather.co'    =>  'I65940.json.schedulesdirect.org',
	'discoveryturbo.co'       =>  'I46608.json.schedulesdirect.org',
	'discoveryworld.co'       =>  'I66488.json.schedulesdirect.org',
	'disneychannel.co'        =>  'I19234.json.schedulesdirect.org',
	'disneyjunior.co'         =>  'I61311.json.schedulesdirect.org',
	'disneyxd.co'             =>  'I16563.json.schedulesdirect.org',
	'dw.co'                   =>  'I64230.json.schedulesdirect.org',
	'dwamerika.co'            =>  'I74479.json.schedulesdirect.org',
	'entertaiment.co'         =>  'I101734.json.schedulesdirect.org',	
	'sembrador.co'            =>  '',
	'enlace.co'               =>  'I20286.json.schedulesdirect.org',
	'espn.co'                 =>  '',
	'espn2.co'                =>  'I98533.json.schedulesdirect.org',	
	'espn3.co'                =>  'I73833.json.schedulesdirect.org',
	'espnplus.co'             =>  'I65930.json.schedulesdirect.org',
	'eurochannel.co'          =>  'I16574.json.schedulesdirect.org',
	'ewtn.co'                 =>  'I16350.json.schedulesdirect.org',
	'filmarts.co'             =>  'I16215.json.schedulesdirect.org',
	'fox.co'                  =>  'I88534.json.schedulesdirect.org',
	'foxmx.co'                =>  'I88534.json.schedulesdirect.org',
	'foxaction.co'            =>  'I74574.json.schedulesdirect.org',
	'foxcinema.co'            =>  'I71662.json.schedulesdirect.org',
	'foxclassics.co'          =>  'I44028.json.schedulesdirect.org',
	'foxcomedy.co'            =>  'I90916.json.schedulesdirect.org',
	'foxfamily.co'            =>  'I65399.json.schedulesdirect.org',
	'foxlife.co'              =>  '',
	'foxlife.mx'              =>  'I49263.json.schedulesdirect.org',
	'foxmovies.co'            =>  'I58833.json.schedulesdirect.org',
	'foxnews.co'              =>  'I16374.json.schedulesdirect.org',
	'foxseries.co'            =>  'I18812.json.schedulesdirect.org',
	'foxsports.mx'            =>  'I61704.json.schedulesdirect.org',
	'foxsports2.mx'           =>  'I66365.json.schedulesdirect.org',	
	'foxsports3.mx'           =>  'I105006.json.schedulesdirect.org',
	'foxsports.co'            =>  'I30262.json.schedulesdirect.org',  
	'foxsports2.co'           =>  'I105404.json.schedulesdirect.org',
	'foxsports3.co'           =>  'I47374.json.schedulesdirect.org',
	'france24.co'             =>  'I105781.json.schedulesdirect.org',
	'fx.co'                   =>  '',
	'fx.mx'                   =>  'I46442.json.schedulesdirect.org',
	'fxm.co'                  =>  'I105767.json.schedulesdirect.org',	
	'fxm.mx'                  =>  'I105767.json.schedulesdirect.org',
	'glitz.co'                =>  'I61514.json.schedulesdirect.org',
    'goldenplus.co'           =>  'I68317.json.schedulesdirect.org',
    'golden.co'               =>  'I50709.json.schedulesdirect.org',
	'goldenpremier.co'        =>  'I80596.json.schedulesdirect.org',
	'gourmet.co'              =>  'I45910.json.schedulesdirect.org',
	'h2.co'                   =>  'I100668.json.schedulesdirect.org',
	'hbo.co'                  =>  'I12288.json.schedulesdirect.org',
	'hbo2.co'                 =>  'I80113.json.schedulesdirect.org',
	'hbofamily.co'            =>  'I80118.json.schedulesdirect.org',
	'hboplus.co'              =>  'I75537.json.schedulesdirect.org',
	'hbosigna.co'             =>  'I74450.json.schedulesdirect.org', 	
	'headline.co'             =>  'I10145.json.schedulesdirect.org',
	'history.co'              =>  'I101575.json.schedulesdirect.org',
	'holatv.co'               =>  'I92054.json.schedulesdirect.org',
	'htv.co'                  =>  'I15969.json.schedulesdirect.org',
	'ibero.co'                =>  '',
	'inti.co'                 =>  'I82162.json.schedulesdirect.org',
	'estrellas.co'            =>  'I16257.json.schedulesdirect.org',
	'lifetime.co'             =>  'I100088.json.schedulesdirect.org',
	'maschic.co'              =>  'I17457.json.schedulesdirect.org',
	'max.co'                  =>  'I68119.json.schedulesdirect.org',
	'maxup.co'                =>  'I68301.json.schedulesdirect.org',
	'maxprime.co'             =>  'I80211.json.schedulesdirect.org',
	'mtv.co'                  =>  'I12712.json.schedulesdirect.org',
	'mtvhits.co'              =>  'I67787.json.schedulesdirect.org',
	'mtvlive.co'              =>  'I66419.json.schedulesdirect.org',
	'multipremier.co'         =>  'I18169.json.schedulesdirect.org',
	'natgeo.co'               =>  '',	
	'natgeo.mx'               =>  'I25068.json.schedulesdirect.org',	
	'natgeokids.mx'           =>  'I105877.json.schedulesdirect.org',
	'natgeokids.co'           =>  'I104524.json.schedulesdirect.org',
	'natgeowild.co'           =>  'I67590.json.schedulesdirect.org',
	'nick.co'                 =>  'I49896.json.schedulesdirect.org',
	'nick2.co'                =>  'I77783.json.schedulesdirect.org',
	'nickjunior.co'           =>  'I60295.json.schedulesdirect.org',
	'ntn24.co'                =>  'I61988.json.schedulesdirect.org',
	'paramount.co'            =>  'I91029.json.schedulesdirect.org',
	'pasiones.co'             =>  'I71621.json.schedulesdirect.org',
	'radiola.co'              =>  'I111167.json.schedulesdirect.org',	
	'rai.co'                  =>  'I19040.json.schedulesdirect.org',
	'rcn.co'                  =>  'I18568.json.schedulesdirect.org',
	'rcnnovelas.co'           =>  '',
	'red.co'                  =>  'I75213.json.schedulesdirect.org',	
	'sony.co'                 =>  'I19385.json.schedulesdirect.org',
	'space.co'                =>  'I66349.json.schedulesdirect.org',
	'studiouniversal.co'      =>  'I29017.json.schedulesdirect.org',
	'sundance.co'             =>  'I82755.json.schedulesdirect.org',
	'syfy.co'                 =>  'I56727.json.schedulesdirect.org',
	'tbs.co'                  =>  'I75073.json.schedulesdirect.org',
	'tcm.co'                  =>  'I19246.json.schedulesdirect.org',
	'teleamiga.co'            =>  'I61017.json.schedulesdirect.org',
	'teleantioquia.co'        =>  'I30402.json.schedulesdirect.org',
	'telecafe.co'             =>  'I55832.json.schedulesdirect.org',
	'telecaribe.co'           =>  'I55427.json.schedulesdirect.org',
	'telefe.co'               =>  'I16189.json.schedulesdirect.org',
	'telemundo.co'            =>  'I64835.json.schedulesdirect.org',
	'telepacifico.co'         =>  'I18099.json.schedulesdirect.org',
	'tlnovelas.co'            =>  'I37232.json.schedulesdirect.org',
	'tnt.co'                  =>  'I15914.json.schedulesdirect.org',
	'tntseries.co'            =>  'I92090.json.schedulesdirect.org',
	'tooncast.co'             =>  'I63109.json.schedulesdirect.org',
	'tro.co'                  =>  '',
	'trutv.co'                =>  'I16496.json.schedulesdirect.org',	
	'tv5.co'                  =>  'I16422.json.schedulesdirect.org',
	'tvagro.co'               =>  'I63720.json.schedulesdirect.org',
	'tvnchile.co'             =>  'I16046.json.schedulesdirect.org',
	'tve.co'                  =>  'I16217.json.schedulesdirect.org',
	'unicable.co'             =>  'I16521.json.schedulesdirect.org',
	'universalchannel.co'     =>  'I16799.json.schedulesdirect.org',
	'veplustv.co'             =>  'I81483.json.schedulesdirect.org',
	'vh1hd.co'                =>  'I88942.json.schedulesdirect.org',
	'vh1.co'                  =>  'I42567.json.schedulesdirect.org',	
	'vh1classic.co'           =>  'I90325.json.schedulesdirect.org', 
	'warner.co'               =>  'I16213.json.schedulesdirect.org',
	'winsports.co'            =>  'I87031.json.schedulesdirect.org',
	
);

my $search = join( "|", map {quotemeta} sort { length ($b) <=> length ($a) } keys %replace );
$search = qr/\b($search)\b/;

while (<>) {
    s/$search/$replace{$1}/g;
    print;
}



	
